spring:
  datasource:
    url: jdbc:postgresql://localhost:5632/socialmedia
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8086
